export type productos = {
  id_producto: number;
  id_tienda: number;
  id_categoría: number;
  id_fotos_galeria: string;
  nombre_producto: string;
  descripcion_producto: string;
  foto_principal: string;
  precio: string;
  stock: number;
};

const productosList: productos[] = [
  //Categoría 1
  {
    id_producto: 1,
    id_tienda: 1,
    id_categoría: 1,
    id_fotos_galeria: 'gallery1',
    nombre_producto: 'Collar de plata',
    descripcion_producto: 'Collar hecho a mano con plata de alta calidad.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '25.00',
    stock: 50,
  },
  {
    id_producto: 2,
    id_tienda: 2,
    id_categoría: 1,
    id_fotos_galeria: 'gallery2',
    nombre_producto: 'Anillo de oro',
    descripcion_producto: 'Elegante anillo de oro con incrustaciones de diamante.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '120.00',
    stock: 20,
  },
  {
    id_producto: 3,
    id_tienda: 3,
    id_categoría: 1,
    id_fotos_galeria: 'gallery3',
    nombre_producto: 'Pulsera de cuero',
    descripcion_producto: 'Pulsera hecha a mano con cuero genuino.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '15.00',
    stock: 100,
  },
  {
    id_producto: 4,
    id_tienda: 4,
    id_categoría: 1,
    id_fotos_galeria: 'gallery4',
    nombre_producto: 'Pendientes de perlas',
    descripcion_producto: 'Pendientes elegantes con perlas cultivadas.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '30.00',
    stock: 75,
  },
  {
    id_producto: 5,
    id_tienda: 5,
    id_categoría: 1,
    id_fotos_galeria: 'gallery5',
    nombre_producto: 'Broche de cristal',
    descripcion_producto: 'Broche decorativo con cristales brillantes.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '40.00',
    stock: 60,
  },
  {
    id_producto: 6,
    id_tienda: 6,
    id_categoría: 1,
    id_fotos_galeria: 'gallery6',
    nombre_producto: 'Collar de piedras preciosas',
    descripcion_producto: 'Collar con piedras preciosas de varios colores.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '85.00',
    stock: 30,
  },
  {
    id_producto: 7,
    id_tienda: 7,
    id_categoría: 1,
    id_fotos_galeria: 'gallery7',
    nombre_producto: 'Anillo de plata y ónix',
    descripcion_producto: 'Anillo de plata con piedra de ónix negro.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '50.00',
    stock: 40,
  },
  {
    id_producto: 8,
    id_tienda: 8,
    id_categoría: 1,
    id_fotos_galeria: 'gallery8',
    nombre_producto: 'Pendientes de turquesa',
    descripcion_producto: 'Pendientes colgantes con piedras de turquesa.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '20.00',
    stock: 80,
  },
  {
    id_producto: 9,
    id_tienda: 1,
    id_categoría: 1,
    id_fotos_galeria: 'gallery9',
    nombre_producto: 'Pulsera de amatista',
    descripcion_producto: 'Pulsera con cuentas de amatista.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '35.00',
    stock: 50,
  },
  {
    id_producto: 10,
    id_tienda: 2,
    id_categoría: 1,
    id_fotos_galeria: 'gallery10',
    nombre_producto: 'Collar de coral',
    descripcion_producto: 'Collar artesanal con piezas de coral.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '45.00',
    stock: 40,
  },

  //Categoria 2
  {
    id_producto: 11,
    id_tienda: 3,
    id_categoría: 2,
    id_fotos_galeria: 'gallery11',
    nombre_producto: 'Vela aromática',
    descripcion_producto: 'Vela artesanal con aroma a lavanda.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '15.00',
    stock: 100,
  },
  {
    id_producto: 12,
    id_tienda: 4,
    id_categoría: 2,
    id_fotos_galeria: 'gallery12',
    nombre_producto: 'Jarrón de cerámica',
    descripcion_producto: 'Jarrón decorativo hecho a mano.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '25.00',
    stock: 80,
  },
  {
    id_producto: 13,
    id_tienda: 5,
    id_categoría: 2,
    id_fotos_galeria: 'gallery13',
    nombre_producto: 'Cojín bordado',
    descripcion_producto: 'Cojín decorativo con bordados tradicionales.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '20.00',
    stock: 90,
  },
  {
    id_producto: 14,
    id_tienda: 6,
    id_categoría: 2,
    id_fotos_galeria: 'gallery14',
    nombre_producto: 'Espejo vintage',
    descripcion_producto: 'Espejo con marco de madera tallada.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '50.00',
    stock: 40,
  },
  {
    id_producto: 15,
    id_tienda: 7,
    id_categoría: 2,
    id_fotos_galeria: 'gallery15',
    nombre_producto: 'Alfombra tejida',
    descripcion_producto: 'Alfombra artesanal de lana.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '60.00',
    stock: 30,
  },
  {
    id_producto: 16,
    id_tienda: 8,
    id_categoría: 2,
    id_fotos_galeria: 'gallery16',
    nombre_producto: 'Cuadro pintado a mano',
    descripcion_producto: 'Pintura decorativa sobre lienzo.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '80.00',
    stock: 20,
  },
  {
    id_producto: 17,
    id_tienda: 1,
    id_categoría: 2,
    id_fotos_galeria: 'gallery17',
    nombre_producto: 'Lampara de mesa',
    descripcion_producto: 'Lámpara con base de cerámica y pantalla de lino.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '45.00',
    stock: 70,
  },
  {
    id_producto: 18,
    id_tienda: 2,
    id_categoría: 2,
    id_fotos_galeria: 'gallery18',
    nombre_producto: 'Reloj de pared',
    descripcion_producto: 'Reloj decorativo con diseño vintage.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '35.00',
    stock: 60,
  },
  {
    id_producto: 19,
    id_tienda: 3,
    id_categoría: 2,
    id_fotos_galeria: 'gallery19',
    nombre_producto: 'Marco para fotos',
    descripcion_producto: 'Marco de madera tallada para fotos.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '15.00',
    stock: 50,
  },
  {
    id_producto: 20,
    id_tienda: 4,
    id_categoría: 2,
    id_fotos_galeria: 'gallery20',
    nombre_producto: 'Florero de vidrio',
    descripcion_producto: 'Florero hecho a mano con vidrio reciclado.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '20.00',
    stock: 70,
  },

  //Categoría 3
  {
    id_producto: 21,
    id_tienda: 5,
    id_categoría: 3,
    id_fotos_galeria: 'gallery21',
    nombre_producto: 'Bufanda de lana',
    descripcion_producto: 'Bufanda tejida a mano con lana de alpaca.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '30.00',
    stock: 60,
  },
  {
    id_producto: 22,
    id_tienda: 6,
    id_categoría: 3,
    id_fotos_galeria: 'gallery22',
    nombre_producto: 'Sombrero de fieltro',
    descripcion_producto: 'Sombrero elegante hecho de fieltro.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '25.00',
    stock: 40,
  },
  {
    id_producto: 23,
    id_tienda: 7,
    id_categoría: 3,
    id_fotos_galeria: 'gallery23',
    nombre_producto: 'Chaqueta de cuero',
    descripcion_producto: 'Chaqueta de cuero genuino con detalles en metal.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '150.00',
    stock: 30,
  },
  {
    id_producto: 24,
    id_tienda: 8,
    id_categoría: 3,
    id_fotos_galeria: 'gallery24',
    nombre_producto: 'Camisa de lino',
    descripcion_producto: 'Camisa ligera de lino con botones de madera.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '40.00',
    stock: 70,
  },
  {
    id_producto: 25,
    id_tienda: 1,
    id_categoría: 3,
    id_fotos_galeria: 'gallery25',
    nombre_producto: 'Pantalones de mezclilla',
    descripcion_producto: 'Pantalones de mezclilla con ajuste cómodo.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '60.00',
    stock: 50,
  },
  {
    id_producto: 26,
    id_tienda: 2,
    id_categoría: 3,
    id_fotos_galeria: 'gallery26',
    nombre_producto: 'Gorra de algodón',
    descripcion_producto: 'Gorra ajustable de algodón con bordado.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '15.00',
    stock: 90,
  },
  {
    id_producto: 27,
    id_tienda: 3,
    id_categoría: 3,
    id_fotos_galeria: 'gallery27',
    nombre_producto: 'Guantes de lana',
    descripcion_producto: 'Guantes de lana con forro suave.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '20.00',
    stock: 80,
  },
  {
    id_producto: 28,
    id_tienda: 4,
    id_categoría: 3,
    id_fotos_galeria: 'gallery28',
    nombre_producto: 'Cinturón de cuero',
    descripcion_producto: 'Cinturón de cuero hecho a mano.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '25.00',
    stock: 70,
  },
  {
    id_producto: 29,
    id_tienda: 5,
    id_categoría: 3,
    id_fotos_galeria: 'gallery29',
    nombre_producto: 'Jersey de punto',
    descripcion_producto: 'Jersey de punto suave y cálido.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '45.00',
    stock: 50,
  },
  {
    id_producto: 30,
    id_tienda: 6,
    id_categoría: 3,
    id_fotos_galeria: 'gallery30',
    nombre_producto: 'Botines de ante',
    descripcion_producto: 'Botines de ante con suela antideslizante.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '80.00',
    stock: 40,
  },

  //Categoría 4 
  {
    id_producto: 31,
    id_tienda: 7,
    id_categoría: 4,
    id_fotos_galeria: 'gallery31',
    nombre_producto: 'Agenda de cuero',
    descripcion_producto: 'Agenda de cuero auténtico con hojas de papel reciclado.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '35.00',
    stock: 50,
  },
  {
    id_producto: 32,
    id_tienda: 8,
    id_categoría: 4,
    id_fotos_galeria: 'gallery32',
    nombre_producto: 'Bolígrafo de metal',
    descripcion_producto: 'Bolígrafo de metal con acabado en oro.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '10.00',
    stock: 100,
  },
  {
    id_producto: 33,
    id_tienda: 1,
    id_categoría: 4,
    id_fotos_galeria: 'gallery33',
    nombre_producto: 'Bloc de notas',
    descripcion_producto: 'Bloc de notas con hojas perforadas y tapas de cartón.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '8.00',
    stock: 75,
  },
  {
    id_producto: 34,
    id_tienda: 2,
    id_categoría: 4,
    id_fotos_galeria: 'gallery34',
    nombre_producto: 'Organizador de escritorio',
    descripcion_producto: 'Organizador de escritorio de madera con compartimentos.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '25.00',
    stock: 40,
  },
  {
    id_producto: 35,
    id_tienda: 3,
    id_categoría: 4,
    id_fotos_galeria: 'gallery35',
    nombre_producto: 'Reloj de escritorio',
    descripcion_producto: 'Reloj de escritorio con base de mármol y esfera dorada.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '50.00',
    stock: 30,
  },
  {
    id_producto: 36,
    id_tienda: 4,
    id_categoría: 4,
    id_fotos_galeria: 'gallery36',
    nombre_producto: 'Portafolios de cuero',
    descripcion_producto: 'Portafolios de cuero con múltiples compartimentos.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '70.00',
    stock: 20,
  },
  {
    id_producto: 37,
    id_tienda: 5,
    id_categoría: 4,
    id_fotos_galeria: 'gallery37',
    nombre_producto: 'Calculadora solar',
    descripcion_producto: 'Calculadora con energía solar y teclas grandes.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '15.00',
    stock: 85,
  },
  {
    id_producto: 38,
    id_tienda: 6,
    id_categoría: 4,
    id_fotos_galeria: 'gallery38',
    nombre_producto: 'Set de marcadores',
    descripcion_producto: 'Set de 12 marcadores de colores con punta de fieltro.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '12.00',
    stock: 100,
  },
  {
    id_producto: 39,
    id_tienda: 7,
    id_categoría: 4,
    id_fotos_galeria: 'gallery39',
    nombre_producto: 'Tijeras de oficina',
    descripcion_producto: 'Tijeras de oficina con hojas de acero inoxidable.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '9.00',
    stock: 60,
  },
  {
    id_producto: 40,
    id_tienda: 8,
    id_categoría: 4,
    id_fotos_galeria: 'gallery40',
    nombre_producto: 'Archivador de anillas',
    descripcion_producto: 'Archivador de anillas con capacidad para 500 hojas.',
    foto_principal: 'https://via.placeholder.com/150',
    precio: '20.00',
    stock: 45,
  },
];

export const getProductoById = async (
  idProducto: number,
): Promise<productos> => {
  return productosList.find((p) => p.id_producto === idProducto)!;
};

export const getProductos = async (): Promise<productos[]> => {
  return productosList;
};
